library(data.table)
options(warn=-1)
fc = fread("household_power_consumption.txt")
fc1=subset(fc,Date=="1/2/2007"|Date=="2/2/2007")
library(dplyr)
fc2<-mutate(fc1,gap=as.numeric(Global_active_power))
fc3<-mutate(fc2,datetime=paste(Date,Time))
dt1=strptime(as.character(fc3$datetime),"%d/%m/%Y %H:%M:%OS")
fc4<-mutate(fc3,sm1=as.numeric(Sub_metering_1))
fc4<-mutate(fc4,sm2=as.numeric(Sub_metering_2))
fc4<-mutate(fc4,sm3=as.numeric(Sub_metering_3))
png(file="plot3.png",width = 480, height = 480)
plot(dt1,fc4$sm1,type="n",xlab="",ylab="Energy sub metering")
lines(dt1,fc4$sm1,col="black")
lines(dt1,fc4$sm2,col="red")
lines(dt1,fc4$sm3,col="blue")
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),legend=c("Sub-metering_1","Sub_metering_2","Sub_metering_3"),cex=0.8)
dev.off()
options(warn=0)

