options(warn=-1)
library(data.table)
library(dplyr)
fc = fread("household_power_consumption.txt")
fc1=subset(fc,Date=="1/2/2007"|Date=="2/2/2007")
fc2<-mutate(fc1,gap=as.numeric(Global_active_power))
fc3<-mutate(fc2,datetime=paste(Date,Time))
dt1=strptime(as.character(fc3$datetime),"%d/%m/%Y %H:%M:%OS")
fc3<-mutate(fc3,v=as.numeric(Voltage))
fc3<-mutate(fc3,sm1=as.numeric(Sub_metering_1))
fc3<-mutate(fc3,sm2=as.numeric(Sub_metering_2))
fc3<-mutate(fc3,sm3=as.numeric(Sub_metering_3))
fc3<-mutate(fc3,grp=as.numeric(Global_reactive_power))
png(file="plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
plot(dt1,fc3$gap,type="l",xlab="",ylab="Global Active Power(kilowatts)")
plot(dt1,fc3$v,type="l",xlab="datetime",ylab="Voltage")
plot(dt1,fc3$sm1,type="n",xlab="",ylab="Energy sub metering")
lines(dt1,fc3$sm1,col="black")
lines(dt1,fc3$sm2,col="red")
lines(dt1,fc3$sm3,col="blue")
legend("topright",lty=c(1,1,1),col=c("black","red","blue"),legend=c("Sub-metering_1","Sub_metering_2","Sub_metering_3"),cex=0.3)
plot(dt1,fc3$grp,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()
options(warn=0)

